const products = [
  {
    _id: '1',
    name: 'Fresh Apples 6 pcs',
    image: '/images/apples.jpg',
    description:
      'Apple is one of the most popular fruits worldwide. It is rich in Fiber, Potassium, Vitamin C, Vitamin K, Carbs and Calories. It also consists of soluble fibers that helps in weight loss and maintaining gut health. Eating apples lower the risks of major diseases like Cancer, Diabetes etc. You can include Apples as a part of your diet in the form of Salads, Smoothies, Pies and several other desserts. Buy Apple Indian 6 pcs (Pack) online now.',
    brand: 'apple',
    category: 'Fruits',
    price: 120,
    countInStock: 5,
    rating: 4.6,
    numReviews: 4,
  },
  {
    _id: '2',
    name: 'Fresh Pomegranate 1kg',
    image: '/images/pomegranate.jpg',
    description:
      'Pomegranates are considered one of the healthiest fruits in the world. It belongs to the Berry family and has an upper skin thats thick and inedible. However, the tiny, juicy seeds inside are the ones that are edible and consists of infinite nutrients and powerful plant compounds. It has excellent anti-inflammatory effects, helps fight Arthritis, Joint pain, Prostate Cancer & Breast Cancer, lowers Blood Pressure and treats Erectile Dysfunction. Buy Pomegranate Kesar 1 kg online now.',
    brand: 'pomegranate',
    category: 'Fruits',
    price: 170,
    countInStock: 5,
    rating: 4,
    numReviews: 4,
  },
  {
    _id: '3',
    name: 'Tender Coconut 1 pc',
    image: '/images/tendercoconut.jpg',
    description:
      'Coconut is another power packed fruit rich in nutrients that originates from the Tropical region. It is consumed globally in different forms like Coconut Milk, Coconut Water, Coconut Oil etc. Coconut Oil is medically recommended for neutralizing Cholesterol levels. Theres a raw white meat inside the Coconut shell which is known as the Kernel. The Kernel is the edible, sweet tasting part of the Coconut which has firm texture and is delicious.',
    brand: 'coconut',
    category: 'Fruits',
    price: 40,
    countInStock: 5,
    rating: 5,
    numReviews: 4,
  },
  {
    _id: '4',
    name: 'Tata Iodised Salt 1 kg ',
    image: '/images/tatasalt.jpeg',
    description:
      'Salt is an important ingredient used in cooking any meal, be it traditional desi khana or continental food, as it adds the requisite flavour to dishes. Tata Iodised Salt is the best choice for everyday cooking, has a plethora of health benefits and is a great addition to your diet for maintaining a healthy lifestyle. ',
    brand: 'tata',
    category: 'salt',
    price: 20,
    countInStock: 5,
    rating: 4.7,
    numReviews: 4,
  },
  {
    _id: '5',
    name: 'Aashirvaad Whole Wheat Atta 10 kg',
    image: '/images/atta.jpeg',
    description:
      'Aashirvaad Whole Wheat Atta provides the goodness of health in every bite. This product incorporates many benefits of wheat and lets your body maintain a nutrient balance. It is made of nutritious wheat grains. Also, it has a sweet taste that gives you fuller and softer rotis, every single time. Buy Aashirvaad Whole Wheat Atta online now.',
    brand: 'Aashirvaad',
    category: 'Staples',
    price: 400,
    countInStock: 5,
    rating: 4,
    numReviews: 4,
  },
  {
    _id: '6',
    name: 'Amul Pasteurised Butter 500 g (Carton)',
    image: '/images/amulbutter.jpeg',
    description:
      'Who doesnt like a chunk of creamy, velvety, smooth and mouth-watering butter? Made with fresh ingredients, Amul Pasteurised Butter is a multi-purpose butter that can be used as a spread on bread, paratha, roti, naan and sandwiches.',
    brand: 'Amul',
    category: 'dairy',
    price: 235,
    countInStock: 5,
    rating: 4.5,
    numReviews: 4,
  },
  {
    _id: '7',
    name: 'Amul Pure Ghee 1 L (Pouch)',
    image: '/images/amulghee.jpg',
    description:
      'For all your cooking needs, look no further than Amul Pure Ghee. With a long shelf-life and rich aroma, this is an ideal product for your kitchen and serves as a good Vitamin A source. It is clarified butter in its purest form and you can use it for a variety of purposes.',
    brand: 'Amul',
    category: 'Dairy',
    price: 485,
    countInStock: 5,
    rating: 4.6,
    numReviews: 4,
  },
  {
    _id: '8',
    name: 'Parle-G Gold Biscuits 1 kg',
    image: '/images/parleg.jpeg',
    description:
      'Filled with the goodness of milk and wheat, Parle-G has been a source of all-round nourishment for the nation since decades. They’re crispy, they’re tasty and they’ll leave you craving for more. Parle G Biscuits have been an all-time favourite across people of all ages.',
    brand: 'Parle',
    category: 'Snacks',
    price: 115,
    countInStock: 5,
    rating: 4.6,
    numReviews: 4,
  },
];
export default products;